# Generated by Django 3.1.1 on 2020-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('done', 'Done')], max_length=10, verbose_name='Status')),
            ],
        ),
    ]
